name: video_player_for_web_integration_tests
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: 6.3.0+atsumi
  video_player_web:
    path: ../
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
