name: vp_app
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.9.0

dev_dependencies:
  melos: ^7.0.0

melos:
  scripts:
    generate:
      run: |
        melos exec --depends-on build_runner -- dart run build_runner build
        melos exec --depends-on pigeon -- dart run pigeon --input pigeons/messages.dart

workspace:
  - video_player
  - video_player/example
  - video_player_android
  - video_player_android/example
  - video_player_avfoundation
  - video_player_avfoundation/example
  - video_player_platform_interface
  - video_player_web
  - video_player_web/example
