name: video_player_android_example
description: Demonstrates how to use the video_player plugin.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  video_player_android: 2.8.2+atsumi
  video_player_platform_interface: 6.3.0+atsumi

dev_dependencies:
  espresso: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: any
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
